export const FETCH_SUMMARY_DATA = 'FETCH_SUMMARY_DATA';
export const SUCCESS_SUMMARY_DATA = 'SUCCESS_SUMMARY_DATA';
export const FAIL_SUMMARY_DATA = 'FAIL_SUMMARY_DATA';

export const FETCH_USER_MGMT_DATA = 'FETCH_USER_MGMT_DATA';
export const SUCCESS_USER_MGMT_DATA = 'SUCCESS_USER_MGMT_DATA';
export const FAIL_USER_MGMT_DATA = 'FAIL_USER_MGMT_DATA';

export const FETCH_DEVICE_MGMT_DATA = 'FETCH_DEVICE_MGMT_DATA';
export const SUCCESS_DEVICE_MGMT_DATA = 'SUCCESS_DEVICE_MGMT_DATA';
export const FAIL_DEVICE_MGMT_DATA = 'FAIL_DEVICE_MGMT_DATA';

export const FETCH_HOME_MGMT_DATA = 'FETCH_HOME_MGMT_DATA';
export const SUCCESS_HOME_MGMT_DATA = 'SUCCESS_HOME_MGMT_DATA';
export const FAIL_HOME_MGMT_DATA = 'FAIL_HOME_MGMT_DATA';

