export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const SUCCESS_USER_DATA = 'SUCCESS_USER_DATA';
export const FAIL_USER_DATA = 'FAIL_USER_DATA';
export const RESET_USER_DATA = 'RESET_USER_DATA';
export const SET_USER_EXPIRED = 'SET_USER_SESSION_EXPIRED';
export const RESET_USER_EXPIRED = 'RESET_USER_EXPIRED';
